USE BOOKINGS_PROJECT;
GO
--DUPLICATE ANALYSIS
WITH RankedBookings AS (
    SELECT *,
           ROW_NUMBER() OVER (
               PARTITION BY Booking_ID
               ORDER BY [Date], [Time]
           ) AS rn
    FROM BOOKINGS
)
SELECT COUNT(*) AS DuplicatesRemoved
FROM RankedBookings
WHERE rn > 1;

SELECT * FROM BOOKINGS;

--CREATING A PICKUP TIMESTAMP FROM DATE AND TIME
ALTER TABLE BOOKINGS
ADD pickup_ts DATETIME;
UPDATE BOOKINGS
SET pickup_ts= CAST([Date] AS DATETIME) + CAST([Time] AS DATETIME);

--DERIVE DAY OF THE WEEK AND HOUR OF THE DAY FROM TIMESATMP
ALTER TABLE BOOKINGS
ADD Day_of_Week AS DATENAME (WEEKDAY, [pickup_ts]);
ALTER TABLE BOOKINGS
ADD Hour_of_Day AS DATEPART (HH, [pickup_ts]);

--CREATE A ROUTE COLUMN SHOWING PICKUP AND DROP-OFF ROUTE
ALTER TABLE BOOKINGS
ADD Route AS Pickup_Location + ' -> ' + Drop_Location;

--CREATING A PAYMENT METHOD COLUMN WHERE ITS NORMALISED TO UPPERCASE LETTERS AND REMOVING ANY SPACES
ALTER TABLE BOOKINGS
ADD Payment_Method_Norm AS UPPER(REPLACE (TRIM([Payment_Method]),'',''));

--CREATING A DUPLICATE TABLE CALL BOOKINGS_CLEAN
SELECT 
[PICKUP_TS],
[DAY_OF_WEEK],
[HOUR_OF_DAY],
[ROUTE],
[PAYMENT_METHOD_NORM] 
INTO BOOKINGS_CLEAN
FROM BOOKINGS;

SELECT * FROM BOOKINGS_CLEAN
